name: 'ðŸ“¦ Publish Vivid'

on: workflow_call

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'

      - name: Bump
        # TODO: replace once 3rd version is stable and published
        # run: npm version prerelease --preid=next.${{ env.short_head }} --tag next --no-git-tag-version --no-push
        run: npm version 3.0.0-next.${{ env.short_head }} --tag next --no-git-tag-version --no-push
        env:
          short_head: $(git rev-parse --short HEAD)

      - name: Publish
        run: npm publish --access public --tag next --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
