name: upload-icons
on: workflow_dispatch

jobs:
  upload-icons:
    name: upload-icons-to-cdn
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload assets
      uses: ./.github/actions/upload-icons
      with:
        bucket: 'vivid-icons-dev'
        base-folder: 'NEW_UPLOAD_TEST'
        version: 12
        source-dirs: |
          ./libs/icons/
          ./libs/icons-flag/
          ./libs/icons-brand/
